config_path: !!python/object/apply:pathlib.PosixPath
- config
- swebp.yaml
dataset_name: ''
deployment_install_pipx: false
deployment_startup_timeout: 600
deployment_type: modal
environment_class: null
filter_spec: .*
instances_path: !!python/object/apply:pathlib.PosixPath
- data
- swebench_pro_mini_example_instances.yaml
model: litellm_proxy/anthropic/claude-sonnet-4-5
model_api_base: https://litellm.ml-serving-internal.scale.com/v1
model_api_key: sk-pIlJdNIuscEB6oTnqXt2hw
model_class: null
model_temperature: null
model_top_p: null
output_dir: !!python/object/apply:pathlib.PosixPath
- msweagent_results
- swebench_pro_mini_example
per_instance_call_limit: 250
per_instance_cost_limit: 0.0
raise_exceptions: false
random_delay_multiplier: 0.5
redo_existing: false
shuffle: false
slice_spec: ''
source: file
split: dev
subset: lite
total_cost_limit: 0.0
workers: 2
